config/routes.rb
Qrtura::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  root to: 'welcome#index'
  resources :pages, only: :show

  get 'admin' => "admin/sessions#new"
  namespace :admin do
    resource :sessions, only: [ :new, :create, :destroy ]
    resources :pages
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  attr_accessible :login,
                  :password

  validates :login, length: { minimum: 3, maximum: 8 }
  validates :password, length: { minimum: 3, maximum: 16 }
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, :to => :data
  
  validates_presence_of :data
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, :mount_on => :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :text,
                  :title

  validates :text, presence: true
  validates :title, presence: true
end

app/controllers/admin/pages_controller.rb
class Admin::PagesController < ApplicationController
  def index
    @pages = Page.all
  end

  def new
    @page = Page.new
  end

  def edit
    @page = Page.find params[:id]
  end

  def create
    @page = Page.new params[:page]
    if @page.save
      redirect_to @page, flash: :success
    else
      render action: :new, flash: :error
    end
  end

  def update
    @page = Page.find params[:id]
    if @page.update_attributes params[:page]
      redirect_to @page, flash: :success
    else
      render action: :edit, flash: :error
    end
  end

  def destroy
    @page = Page.find params[:id]
    @page.destroy
    redirect_to admin_pages_path, flash: :success
  end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < ApplicationController
  def new
    if admin_signed_in?
      redirect_to admin_pages_path
    else
      @admin = Admin.new
    end
  end

  def create
    @admin = Admin.find_by_login params[:admin][:login]
    if @admin && authenticate_admin?(@admin, params[:admin][:password])
      admin_sign_in @admin
      redirect_to admin_pages_path, flash: :success
    else
      @admin = Admin.new params[:admin]
      flash[:notice] = t('wrong_login')
      render action: :new
    end
  end

  def destroy
    admin_sign_out
    redirect_to :root, flash: :success
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include AuthHelper
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    @page = Page.find params[:id]
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/admin/pages_helper.rb
module Admin::PagesHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  include AuthHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/pages/_form.html.haml
= simple_form_for @page, url: admin_pages_path, html: { class: 'form-horizontal' } do |f|
  - f.with_options input_html: { class: :span6 } do |f|
    = f.input :title, as: :string
    = f.label :text
    = f.cktext_area :text
  .form-actions
    = f.button :submit, class: 'btn btn-primary'
    = link_to t('cancel', default: t("helpers.links.cancel")), admin_pages_path, class: 'btn'

app/views/admin/pages/edit.html.haml
- model_class = Page
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/admin/pages/index.html.haml
- model_class = Page
.page-header
  %h1=t '.title'
= link_to t('new', default: t("helpers.links.new")), new_admin_page_path, class: 'btn btn-primary'
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:title)
      %th=t '.actions', default: t("helpers.actions")
  %tbody
    - @pages.each do |page|
      %tr
        %td= link_to page.id, page_path(page)
        %td= link_to page.title, page_path(page)
        %td
          = link_to t('.edit', default: t("helpers.links.edit")), edit_admin_page_path(page), class: 'btn btn-mini'
          = link_to t('.destroy', default: t("helpers.links.destroy")), admin_page_path(page), method: :delete, data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'btn btn-mini btn-danger'

= link_to t('new', default: t("helpers.links.new")), new_admin_page_path, class: 'btn btn-primary'

app/views/admin/pages/new.html.haml
- model_class = Page
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/layouts/application.html.haml
%html
%head
  %title
    Qrtura
  = stylesheet_link_tag    "application"
  = javascript_include_tag "application"
  = csrf_meta_tags
%body
  .offset1.span8
    = yield
    - if admin_signed_in?
      = link_to t('sign_out'), admin_sessions_path, method: :delete, class: 'btn btn-danger'

app/views/pages/show.html.haml
!= @page.text